-- PROGRESSION 1:

--1. Insert into city
INSERT INTO CITY VALUES (1, 'PUNE');
INSERT INTO CITY VALUES (2, 'MUMBAI');
INSERT INTO CITY VALUES (3, 'BANGLORE');
INSERT INTO CITY VALUES (4, 'CHENNAI');
INSERT INTO CITY VALUES (5, 'MADRAS');

--2. Insert into referee
INSERT INTO REFREE VALUES (1,'STEVE');
INSERT INTO REFREE VALUES (2,'BOB');
INSERT INTO REFREE VALUES (1,'JAMES');
INSERT INTO REFREE VALUES (1,'STUART');
INSERT INTO REFREE VALUES (1,'RICKY');

--3. Insert into innings
INSERT INTO INNINGS VALUES (1, 2);
INSERT INTO INNINGS VALUES (2, 5);
INSERT INTO INNINGS VALUES (3, 4);
INSERT INTO INNINGS VALUES (4, 2);
INSERT INTO INNINGS VALUES (5, 3);

--4. Insert into extra_type
INSERT INTO EXTRA_TYPE VALUES(1, 'david');
INSERT INTO EXTRA_TYPE VALUES(2, 'mathews');
INSERT INTO EXTRA_TYPE VALUES(3, 'dhawan');
INSERT INTO EXTRA_TYPE VALUES(4, 'thomas');
INSERT INTO EXTRA_TYPE VALUES(5, 'BOB');

--5. Insert into skill
INSERT INTO SKILL VALUES(1, 'DEFENCE');
INSERT INTO SKILL VALUES(2, 'ATTACK');
INSERT INTO SKILL VALUES(3, 'FIELDING');
INSERT INTO SKILL VALUES(4, 'ATHLETICS');
INSERT INTO SKILL VALUES(5, 'RUNNING');

--6. Insert into team
INSERT INTO TEAM VALUES(1, 'PUNEKARS' , 'STEVE', 1, 5);
INSERT INTO TEAM VALUES(2, 'WARRIORS' , 'SMITH', 5, 1);
INSERT INTO TEAM VALUES(3, 'TEAM1' , 'SHANE', 2, 7);
INSERT INTO TEAM VALUES(4, 'PLAYERS' , 'WATSON', 4, 4);
INSERT INTO TEAM VALUES(5, 'LIONS' , 'BOB', 1, 5);

--7. Insert into player
INSERT INTO PLAYER VALUES(1, 'AMIT' , 'INDIA' , 2, 5);
INSERT INTO PLAYER VALUES(2, 'AJIT' , 'JAPAN' , 4, 7);
INSERT INTO PLAYER VALUES(3, 'SUMIT' , 'AUSTRALIA' , 6, 9);
INSERT INTO PLAYER VALUES(4, 'SUJEET' , 'NEPAL' , 4, 4);
INSERT INTO PLAYER VALUES(5, 'AMAR' , 'BHUTAN' , 1, 6);

--8. Insert into venue
INSERT INTO VENUE VALUES(1, 'STADIUM1', 5);
INSERT INTO VENUE VALUES(2, 'STADIUM2', 4);
INSERT INTO VENUE VALUES(3, 'STADIUM3', 3);
INSERT INTO VENUE VALUES(4, 'STADIUM4', 2);
INSERT INTO VENUE VALUES(5, 'STADIUM5', 1);

--9. Insert into event
INSERT INTO event VALUES(1,2,2,2,2,2,2,2,2);
INSERT INTO event VALUES(2,2,2,2,2,2,2,2,2);
INSERT INTO event VALUES(3,2,2,2,2,2,2,2,2);
INSERT INTO event VALUES(4,2,2,2,2,2,2,2,2);
INSERT INTO event VALUES(5,2,2,2,2,2,2,2,2);

--10. Insert into extra_event
INSERT INTO EXTRA_EVENT VALUES(1,2,3,4,5);
INSERT INTO EXTRA_EVENT VALUES(2,2,3,4,5);
INSERT INTO EXTRA_EVENT VALUES(3,2,3,4,5);
INSERT INTO EXTRA_EVENT VALUES(4,2,3,4,5);
INSERT INTO EXTRA_EVENT VALUES(5,2,3,4,5);

--11. Insert into outcome
INSERT INTO OUTCOME VALUES(1, 'WIN', 4, 88, 8);
INSERT INTO OUTCOME VALUES(2, 'LOSE', 5, 98, 4);
INSERT INTO OUTCOME VALUES(3, 'TIE', 8, 56, 1);

--12. Insert into game
INSERT INTO GAME VALUES(1, '2020-8-7', 4,5,1,1,2,3,5,4);
INSERT INTO GAME VALUES(2, '2020-7-9', 4,5,1,1,2,3,5,4);
INSERT INTO GAME VALUES(3, '2020-6-6', 4,5,1,1,2,3,5,4);
INSERT INTO GAME VALUES(4, '2020-5-1', 4,5,1,1,2,3,5,4);

--13. Update player table
UPDATE PLAYER 
SET NAME = 'SURESH'
WHERE ID=5;

--14. Update player table
UPDATE PLAYER 
SET COUNTRY = 'CHINA'
WHERE NAME= 'AMAR';

--15. Update player table
UPDATE PLAYER 
SET ID = 40
WHERE SKILL_ID = 5;

--16. Update player table
UPDATE PLAYER 
SET SKILL_ID = 9
WHERE TEAM_ID= 4;

--17. Delete from extra_type
DELETE FROM EXTRA_TYPE
WHERE NAME = 'DHAWAN';

--18. Delete from referee
DELETE FROM REFREE
WHERE ID=2;

--19. Delete from player
DELETE FROM PLAYER
WHERE COUNTRY='AUSTRALIA';

--20. Delete from outcome
DELETE FROM OUTCOME
WHERE STATUS = 'TIE';